### ISSUE TITLE
issue installing HPM

### ISSUE THREAD

**Issue by designMoreWeb** [zeit/hpm#55]
So i had hpm working fine and suddenly it stopped working giving me the error
<img width="1030" alt="screen shot 2016-12-09 at 12 52 01 am" src="https://cloud.githubusercontent.com/assets/5986856/21039151/bb1cb4c4-bda9-11e6-8de0-f1302f699cc7.png">

so i uninstalled HPM and re-installed it when i reinstalled it the error i got was 
<img width="946" alt="screen shot 2016-12-09 at 12 51 16 am" src="https://cloud.githubusercontent.com/assets/5986856/21039158/cc1dffa8-bda9-11e6-806c-962545267ae4.png">

Sorry for the small text on the image but it was the best way to get a whole source tree map of the install. 

I am stuck and i wanted to get this fixed please help me out 

thanks

**Comment by luke3butler** [comment]
I'm getting the same error, except when I reinstall I don't get any unmet dependencies.

Reinstalling doesn't fix the issue.

**Comment by luke3butler** [comment]
@designMoreWeb Check your hyper config file. I restored mine to an earlier version which fixed the issue.

**Comment by alisonmonteiro** [comment]
@designMoreWeb could you please try a new installation using the `-g` flag?

Currently you're using this:

![Currently](https://cloud.githubusercontent.com/assets/3016692/21112571/ff487e8e-c084-11e6-88e2-d29534fb3bb2.png)

Try this: 

```
npm install -g hpm-cli
```

**Comment by designMoreWeb** [comment]
@alisonmonteiro I tried the -g but when i run hpm again i get 
<img width="1118" alt="screen shot 2016-12-12 at 2 38 22 pm" src="https://cloud.githubusercontent.com/assets/5986856/21113745/bac97788-c078-11e6-8a75-92fac5794012.png">

**Comment by designMoreWeb** [comment]
@luke3butler Can i see your config file maybe i have something in mine which maybe causing trouble

**Comment by daveranan** [comment]
I just had this error:
`/usr/local/lib/node_modules/hpm-cli/node_modules/args/dist/index.js:303
      let { usage, description, defaultValue } = item;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/index.js:6:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)`
Fixed by changing Node versions through NodeNV to 6.0.0

**Comment by luke3butler** [comment]
@designMoreWeb Sorry for the delayed response.

`module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: 'Hack, "DejaVu Sans Mono", "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false,

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    summonShortcut: 'Alt+Super+O',

    hyperline: {
      color: 'black',
      plugins: [
        {
          name: 'hostname',
          options: { color: 'lightBlue' }
        },
        {
          name: 'memory',
          options: { color: 'white' }
        },
        {
          name: 'uptime',
          options: { color: 'lightYellow' }
        },
        {
          name: 'cpu',
          options: {
            colors: {
              high: 'lightRed',
              moderate: 'lightYellow',
              low: 'lightGreen'
            }
          }
        },
        {
          name: 'network',
          options: { color: 'lightCyan' }
        },
        {
          name: 'battery',
          options: {
            colors: { fine: 'lightGreen', critical: 'lightRed' }
          }
        }
      ]
    }

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [
    "hypertheme",
    "hyperline",
    "hyperterm-paste",
    "hyper-materialshell",
    "hyper-simple-vibrancy",
    // "config-hyperterm",
    // 'hyperterm-tab-cwd'
    "hyperterm-summon",
    "hypertitle",
    "hyperterm-clicky",
    "hyperlayout"
  ],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};`

**Comment by luke3butler** [comment]
I'll also note that once `config-hyperterm` was used, it ruined much of my config file.

**Comment by designMoreWeb** [comment]
i tried node version 6.9.2 doesn't work @alisonmonteiro

**Comment by alisonmonteiro** [comment]
Hi @designMoreWeb!

Could you please send us your config file?

**Comment by designMoreWeb** [comment]
Here you go @alisonmonteiro 

Node version is 6.8.1
Hyper version is 1.0.0

[hyper.txt](https://github.com/zeit/hpm/files/650279/hyper.txt)

**Comment by daniellacosse** [comment]
+1, having the same issue. Node version is v7.3.0 (latest stable at time of writing). I also used `config-hyperterm` so maybe that's the root of the issue here.

**Comment by designMoreWeb** [comment]
This issue still hasnt been fixed. I would appreciate if it is fixed i really enjoyed using hpm until i got the issue.

**Comment by manizm** [comment]
I am having the same issue
```
hpm
C:\Users\Asus\AppData\Roaming\nvm\v7.9.0\node_modules\hpm-cli\api.js:41
    throw err
    ^

TypeError: Cannot read property 'value' of undefined
    at Object.<anonymous> (C:\Users\Asus\AppData\Roaming\nvm\v7.9.0\node_modules\hpm-cli\api.js:34:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Asus\AppData\Roaming\nvm\v7.9.0\node_modules\hpm-cli\index.js:17:13)
    at Module._compile (module.js:571:32)
```
My node version: 7.9.0
npm version:  4.2.0
hyper version: 1.3.3

My config file: 
```
// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.
let gitRootFolder = 'C:\\Program Files\\Git'

module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 14,

    // font family with optional fallbacks
    // Menlo, "DejaVu Sans Mono", 
    fontFamily: 'Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BEAM',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instead of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    shell: `${gitRootFolder}\\bin\\bash.exe`,

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {TERM: 'cygwin'},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: true,

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
    summon: {
      hideDock: true,
      hotkey: 'Alt+0'
    }
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: ["hyperpower", "hyperline", "hyper-blink", "hyperterm-summon"],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};
```
