### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by kodescience** [zeit/hpm#63]
hyper term version 1.0.0

running any command returns the following 

```
/usr/local/lib/node_modules/hpm-cli/node_modules/args/dist/index.js:303
      let { usage, description, defaultValue } = item;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/index.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by jacklenox** [comment]
Same happening for me.

**Comment by alisonmonteiro** [comment]
Duplicated with #56
