### ISSUE TITLE
Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by Thebigbignooby** [zeit/hpm#82]
When I do `hpm search blink`

or `hpm install hyper-blink`

**Comment by matheuss** [comment]
@Thebigbignooby please share the complete error

**Comment by Thebigbignooby** [comment]
```
TypeError: Cannot read property 'value' of undefined
    at Object.<anonymous> (C:\nvm\v6.9.2\node_modules\hpm-cli\api.js:34:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\nvm\v6.9.2\node_modules\hpm-cli\index.js:17:13)
    at Module._compile (module.js:570:32)
```

**Comment by cannap** [comment]
same Windows 10

**Comment by brianc118** [comment]
I have the same issue in windows 10. Help would be appreciated.

**Comment by halhenke** [comment]
I might be wrong but from some mucking around it seems like 

https://github.com/zeit/hpm/blob/master/api.js#L32-L34

```javascript
  plugins = properties.find(property => {
    return property.key.name === 'plugins'
  }).value.elements
```

should be:

```javascript
  plugins = properties.find(property => {
    return property.key.value === 'plugins'
  }).value.elements
```

**Comment by arch-master** [comment]
@halhenke That doesn't work for me... Created mockup of exactly what I am seeing [here](https://app.moqups.com/felix.superspy@gmail.com/1cE7CF475B/view?ui=0).

**Comment by meesk** [comment]
Same for MacOS
```
TypeError: Cannot read property 'value' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/api.js:38:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/index.js:17:13)
    at Module._compile (module.js:571:32)
```

**Comment by daenney** [comment]
I've got this too:

```
/Users/daenney/homebrew/lib/node_modules/hpm-cli/api.js:41
    throw err
    ^

TypeError: Cannot read property 'value' of undefined
    at Object.<anonymous> (/Users/daenney/homebrew/lib/node_modules/hpm-cli/api.js:34:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/daenney/homebrew/lib/node_modules/hpm-cli/index.js:17:13)
    at Module._compile (module.js:570:32)
```

The code:

```js
try {
  fileContents = fs.readFileSync(fileName, 'utf8')

  parsedFile = recast.parse(fileContents)

  const expression = parsedFile.program.body[0].expression
  const properties = (expression && expression.right && expression.right.properties) || []
  plugins = properties.find(property => {
    return property.key.name === 'plugins'
  }).value.elements

  localPlugins = properties.find(property => {
    return property.key.name === 'localPlugins'
  }).value.elements
} catch (err) {
  if (err.code !== 'ENOENT') { // ENOENT === !exists()
    throw err
  }
}
```

**Comment by daenney** [comment]
I did some `console.log()`ing and it seems that indeed it needs to be `property.key.value`, not `.name`:

```
Property {
    type: 'Property',
    key: 
     Literal {
       type: 'Literal',
       value: 'localPlugins',
       raw: '"localPlugins"',
       loc: [Object] },
```

It has both `raw` and `value`, but not `name`.

**Comment by jrcharney** [comment]
I can also verify `hpm` breaks too easily.

```
hpm
/usr/local/lib/node_modules/hpm-cli/api.js:41
    throw err
    ^

TypeError: Cannot read property 'value' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/api.js:34:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/index.js:17:13)
    at Module._compile (module.js:569:30)
```

and I uninstalled it and re-installed it.  In uninstalled it the first time around because none of the plugins were working because the `node_modules` folder was never created in the `.hyper_plugins` folder, where none of the plugins would install after they were added to the registry and attempts to fill the registry with `npm install` also didn't resolve the problem.

It's probably easier just to install the plugins using `npm` instead of `hpm` at this point.

**Comment by manizm** [comment]
I am having the same issue. It would be great if it gets fixed.
```
hpm
C:\Users\Asus\AppData\Roaming\nvm\v7.9.0\node_modules\hpm-cli\api.js:41
    throw err
    ^

TypeError: Cannot read property 'value' of undefined
    at Object.<anonymous> (C:\Users\Asus\AppData\Roaming\nvm\v7.9.0\node_modules\hpm-cli\api.js:34:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Asus\AppData\Roaming\nvm\v7.9.0\node_modules\hpm-cli\index.js:17:13)
    at Module._compile (module.js:571:32)
```
My node version: 7.9.0
npm version:  4.2.0
hyper version: 1.3.3

My config file: 
```
// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.
let gitRootFolder = 'C:\\Program Files\\Git'

module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 14,

    // font family with optional fallbacks
    // Menlo, "DejaVu Sans Mono", 
    fontFamily: 'Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BEAM',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instead of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    shell: `${gitRootFolder}\\bin\\bash.exe`,

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {TERM: 'cygwin'},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: true,

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
    summon: {
      hideDock: true,
      hotkey: 'Alt+0'
    }
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: ["hyperpower", "hyperline", "hyper-blink", "hyperterm-summon"],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};
```

**Comment by manizm** [comment]
After consoling what I figured out,
`const expression = parsedFile.program.body[0].expression`
is the culprit. The reason is, it trying to find `.expression` when it does not exist in `parsedFile.program.body[0]`. Although it does exist in `.body[1]`

So I changed the value of `expression` to `parsedFile.program.body[1]` and now hpm works for me..
But, now I got another error `cannot read property 'popup' of null` when I try to open the menu xD

**Comment by AliveDD** [comment]
```
$ sudo npm uninstall -g hpm-cli
removed 132 packages in 0.919s

$ sudo npm install -g hpm-cli
/usr/local/bin/hpm -> /usr/local/lib/node_modules/hpm-cli/index.js
+ hpm-cli@2.0.1
added 132 packages in 5.297s

$ hpm -v
/usr/local/lib/node_modules/hpm-cli/api.js:41
    throw err
    ^

TypeError: Cannot read property 'value' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/api.js:34:5)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/index.js:17:13)
    at Module._compile (module.js:641:30)
```
i has this problem too
