### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by mrillusion** [zeit/hpm#84]
hi i install hpm-cli and after that i write hpm help but i get bellow error

`$ hpm help
/usr/local/lib/node_modules/hpm-cli/node_modules/args/index.js:265
          ...this.details.options.map(opt => opt.usage)
          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/index.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
`
i install the hpm-cli like this:
`sudo npm install hpm-cli
/home/user
└── hpm-cli@2.0.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/user/package.json'
npm WARN user No description
npm WARN user No repository field.
npm WARN user No README data
npm WARN user No license field.
`
what should i do for fixing it ? 
`$ node -v
v4.7.2
$ npm -v
4.5.0
`

**Comment by mrillusion** [comment]
it solved i try to install node with nvm with last version of it and it fixed. thanks for hyper project it's so cool

**Comment by drkpyn** [comment]
I also had this issue with node 4.5.0 and upgrading node to the latest version fixed it.

**Comment by jrcharney** [comment]
Install it GLOBALLY with `-g`.

```
sudo npm install -g hpm-cli
```

It should install at `/usr/local/bin/hpm` afterwards.

**Comment by pietrasiak** [comment]
@jrcharney you should never use sudo to install with npm. If you have to do it, you've messed something up with your files, but others should not follow it :)
