### ISSUE TITLE
Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by paulbrie** [zeit/hpm#93]
When I type `hpm ls` I get this message:
```
TypeError: Cannot read property 'value' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/api.js:34:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/index.js:17:13)
    at Module._compile (module.js:571:32)
```

**Comment by DesignMonkey** [comment]
I get it with everything

**Comment by halhenke** [comment]
I'm not sure if the api changed with regards to what is stored in `~/.hyper.js` and this plugin is out of date or that some of us installed Hyper early on and so the contents of this file no longer match what should be there but this is what I get for the properties value on

https://github.com/zeit/hpm/blob/master/api.js#L31
```
[ Property {
    type: 'Property',
    key: 
     Literal {
       type: 'Literal',
       value: 'config',
       raw: '"config"',
       loc: [Object] },
    computed: false,
    value: ObjectExpression { type: 'ObjectExpression', properties: [Array], loc: [Object] },
    kind: 'init',
    method: false,
    shorthand: false,
    loc: { start: [Object], end: [Object], lines: Lines {}, indent: 2 } },
  Property {
    type: 'Property',
    key: 
     Literal {
       type: 'Literal',
       value: 'modifierKeys',
       raw: '"modifierKeys"',
       loc: [Object] },
    computed: false,
    value: ObjectExpression { type: 'ObjectExpression', properties: [Array], loc: [Object] },
    kind: 'init',
    method: false,
    shorthand: false,
    loc: { start: [Object], end: [Object], lines: Lines {}, indent: 2 } },
  Property {
    type: 'Property',
    key: 
     Literal {
       type: 'Literal',
       value: 'plugins',
       raw: '"plugins"',
       loc: [Object] },
    computed: false,
    value: ArrayExpression { type: 'ArrayExpression', elements: [Array], loc: [Object] },
    kind: 'init',
    method: false,
    shorthand: false,
    loc: { start: [Object], end: [Object], lines: Lines {}, indent: 2 } },
  Property {
    type: 'Property',
    key: 
     Literal {
       type: 'Literal',
       value: 'localPlugins',
       raw: '"localPlugins"',
       loc: [Object] },
    computed: false,
    value: ArrayExpression { type: 'ArrayExpression', elements: [], loc: [Object] },
    kind: 'init',
    method: false,
    shorthand: false,
    loc: { start: [Object], end: [Object], lines: Lines {}, indent: 2 } } ]
```

when we filter for `property.key.name === 'plugins'` this doesnt return anything (`property.key.value === 'plugins'` would return the correct property) and thus the attempt to access value fails.
