### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by zakiaziz** [zeit/hpm#97]
Installed via `npm install -g hpm-cli`. Then when running `hpm` I see:
```
$ hpm

/usr/local/lib/node_modules/hpm-cli/index.js:3
const fs = require('fs')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by njh9417** [comment]
I received the same error as well.
`/usr/local/lib/node_modules/hpm-cli/index.js:3
const fs = require('fs')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3`
