### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by fishpen0** [zeit/hpm#98]
```
$ hpm
/usr/local/lib/node_modules/hpm-cli/node_modules/args/index.js:267
          ...this.details.options.map(opt => opt.usage)
          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/index.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by LindseyB** [comment]
Hey this looks like a dupe of #56 the likely solution is just to update your version of node.

If you are using a system other than windows you can do:

```
npm install -g n
n stable
```

On windows you need to go to the node.js website and download the latest version (which you can do with any OS, but I find n easier to use when updating versions of node.
